name: Release

permissions:
  contents: write
  id-token: write
  attestations: write

on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: attest-test
          target: ${{ matrix.target }}
          include: README.md
          zip: windows
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
          checksum: sha512
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: "**/*.tar.gz,**/*.zip"
